# docker-compose.yaml
version: '3.7'

services:
  tusd:
    image: tusproject/tusd:latest
    ports:
      - "1080:1080"
    volumes:
      - ./tus_data:/data
    command: ["-port", "1080", "-behind-proxy", "-upload-dir", "/data"]
